tomcat:
  env_file: envs
  image: tomcat:7.0
  ports:
      - "8089:8089"
      - "8088:8088"
      - "8080:8080"
  links:
      - postgresql:postgresql
  volumes:
      - /usr/local/tomcat/kimios_home
      - /usr/local/tomcat/conf/tomcat-users.xml
      - /home/kimios-repository
postgresql:
  image: postgres:9.4
  env_file: pgenvs
  ports:
    - "5432"
